// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// //...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp5Ic1LYeADtH4oH63y0_f8Fg_bEfuqII',
    appId: '1:560456966746:web:8cc5c94a301af863072e63',
    messagingSenderId: '560456966746',
    projectId: 'weatherapp-fd96f',
    authDomain: 'weatherapp-fd96f.firebaseapp.com',
    storageBucket: 'weatherapp-fd96f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhfWrlcHh_meyYQqjT57NsCoGZxTDqpN8',
    appId: '1:560456966746:android:2463090b94379231072e63',
    messagingSenderId: '560456966746',
    projectId: 'weatherapp-fd96f',
    storageBucket: 'weatherapp-fd96f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKdcKI13PweaLnDRCQOi4sLJ_vuhpZWUU',
    appId: '1:560456966746:ios:e5c05b94a1eeb00f072e63',
    messagingSenderId: '560456966746',
    projectId: 'weatherapp-fd96f',
    storageBucket: 'weatherapp-fd96f.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKdcKI13PweaLnDRCQOi4sLJ_vuhpZWUU',
    appId: '1:560456966746:ios:e5c05b94a1eeb00f072e63',
    messagingSenderId: '560456966746',
    projectId: 'weatherapp-fd96f',
    storageBucket: 'weatherapp-fd96f.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp5Ic1LYeADtH4oH63y0_f8Fg_bEfuqII',
    appId: '1:560456966746:web:49fec7db06ead54d072e63',
    messagingSenderId: '560456966746',
    projectId: 'weatherapp-fd96f',
    authDomain: 'weatherapp-fd96f.firebaseapp.com',
    storageBucket: 'weatherapp-fd96f.firebasestorage.app',
  );
}
